"""add schedules and google_calendar_config tables

Revision ID: 01ce1a251126
Revises: d30dccaa1022
Create Date: 2026-02-08 11:15:27.442134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ce1a251126'
down_revision: Union[str, Sequence[str], None] = 'd30dccaa1022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Taipei', nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedules_creator_id', 'schedules', ['creator_id'], unique=False)
    op.create_index('ix_schedules_end_time', 'schedules', ['end_time'], unique=False)
    op.create_index('ix_schedules_start_time', 'schedules', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedules_start_time', table_name='schedules')
    op.drop_index('ix_schedules_end_time', table_name='schedules')
    op.drop_index('ix_schedules_creator_id', table_name='schedules')
    op.drop_table('schedules')
    op.drop_table('google_calendar_config')
    # ### end Alembic commands ###
