"""add_role_to_empolyees_relationship(1_to_M)

Revision ID: 25223b345e6a
Revises: 499dc0682db6
Create Date: 2026-01-16 10:52:43.804673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25223b345e6a'
down_revision: Union[str, Sequence[str], None] = '499dc0682db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'role_id')
    # ### end Alembic commands ###
