"""add github_id to users

Revision ID: 41994c6ecff0
Revises: 7b31cfd33080
Create Date: 2026-02-20 16:21:30.754177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41994c6ecff0'
down_revision: Union[str, Sequence[str], None] = '7b31cfd33080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['github_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
