"""add_roles_to_authorities_relationship(M_to_M)

Revision ID: 75e2fa53d9d0
Revises: 25223b345e6a
Create Date: 2026-01-16 11:05:12.420907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e2fa53d9d0'
down_revision: Union[str, Sequence[str], None] = '25223b345e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_authority',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'authority_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_authority')
    # ### end Alembic commands ###
