"""add kafka_messages table

Revision ID: 7b31cfd33080
Revises: cbd89f4070f4
Create Date: 2026-02-20 10:52:33.646113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b31cfd33080'
down_revision: Union[str, Sequence[str], None] = 'cbd89f4070f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kafka_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=True),
    sa.Column('offset', sa.BigInteger(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kafka_messages_received_at', 'kafka_messages', ['received_at'], unique=False)
    op.create_index('idx_kafka_messages_topic', 'kafka_messages', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kafka_messages_topic', table_name='kafka_messages')
    op.drop_index('idx_kafka_messages_received_at', table_name='kafka_messages')
    op.drop_table('kafka_messages')
    # ### end Alembic commands ###
