"""add line_user_id to users

Revision ID: a684e2ee76f5
Revises: 41994c6ecff0
Create Date: 2026-02-25 12:11:54.025629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a684e2ee76f5'
down_revision: Union[str, Sequence[str], None] = '41994c6ecff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('line_user_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['line_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'line_user_id')
    # ### end Alembic commands ###
