"""add approval_requests and approval_steps tables

Revision ID: b8700b70b7f1
Revises: b84748caa10b
Create Date: 2026-02-19 17:23:59.617057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8700b70b7f1'
down_revision: Union[str, Sequence[str], None] = 'b84748caa10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('LEAVE', 'EXPENSE', name='approvaltype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstatus'), server_default='PENDING', nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requests_requester_id', 'approval_requests', ['requester_id'], unique=False)
    op.create_index('ix_approval_requests_status', 'approval_requests', ['status'], unique=False)
    op.create_index('ix_approval_requests_type', 'approval_requests', ['type'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstatus'), server_default='PENDING', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_steps_approver_id', 'approval_steps', ['approver_id'], unique=False)
    op.create_index('ix_approval_steps_request_id', 'approval_steps', ['approval_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_steps_request_id', table_name='approval_steps')
    op.drop_index('ix_approval_steps_approver_id', table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index('ix_approval_requests_type', table_name='approval_requests')
    op.drop_index('ix_approval_requests_status', table_name='approval_requests')
    op.drop_index('ix_approval_requests_requester_id', table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
