"""add account_type column to users table

Revision ID: cbd89f4070f4
Revises: b8700b70b7f1
Create Date: 2026-02-19 17:42:19.833934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd89f4070f4'
down_revision: Union[str, Sequence[str], None] = 'b8700b70b7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.Enum('REAL', 'TEST', 'SYSTEM', name='accounttype'), server_default='REAL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
