"""add avatar to profiles

Revision ID: d30dccaa1022
Revises: b99b881f9bc8
Create Date: 2026-02-06 23:15:16.628033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30dccaa1022'
down_revision: Union[str, Sequence[str], None] = 'b99b881f9bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar')
    # ### end Alembic commands ###
