"""add_mqtt_messages_table

Revision ID: e9afe6eb2868
Revises: b7e3f2a1c9d8
Create Date: 2026-02-13 23:12:27.104331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9afe6eb2868'
down_revision: Union[str, Sequence[str], None] = 'b7e3f2a1c9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mqtt_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('qos', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mqtt_messages_received_at', 'mqtt_messages', ['received_at'], unique=False)
    op.create_index('idx_mqtt_messages_topic', 'mqtt_messages', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mqtt_messages_topic', table_name='mqtt_messages')
    op.drop_index('idx_mqtt_messages_received_at', table_name='mqtt_messages')
    op.drop_table('mqtt_messages')
    # ### end Alembic commands ###
